# 資料模式配置
data_schemas:
  price_data:
    required_fields:
      - timestamp
      - open
      - high
      - low
      - close
      - volume
    
    optional_fields:
      - vwap
      - trade_count
    
    timestamp_format:
      - iso8601
      - unix_seconds
      - unix_milliseconds
    
    timezone: "UTC"
    
    data_types:
      timestamp: "datetime64[ns]"
      open: "float64"
      high: "float64"
      low: "float64"
      close: "float64"
      volume: "float64"
      vwap: "float64"
      trade_count: "int64"
  
  pool_data:
    required_fields:
      - timestamp
    
    optional_fields:
      - sqrtPriceX96
      - tick
      - liquidity
      - volume_token0
      - volume_token1
      - fee_growth_global0X128
      - fee_growth_global1X128
      - fee_tier
      - tvl_usd
    
    timestamp_format:
      - iso8601
      - unix_seconds
      - unix_milliseconds
    
    timezone: "UTC"
    
    data_types:
      timestamp: "datetime64[ns]"
      sqrtPriceX96: "int64"
      tick: "int64"
      liquidity: "float64"
      volume_token0: "float64"
      volume_token1: "float64"
      fee_growth_global0X128: "int64"
      fee_growth_global1X128: "int64"
      fee_tier: "int64"
      tvl_usd: "float64"

# 資料驗證規則
validation:
  price_data:
    min_price: 0.000001
    max_price: 1000000.0
    min_volume: 0.0
    max_volume: 1e12
    max_price_change_pct: 100.0  # 單期最大價格變化百分比
  
  pool_data:
    min_liquidity: 0.0
    max_liquidity: 1e15
    min_tick: -887272
    max_tick: 887272
    min_sqrt_price: 1e-48
    max_sqrt_price: 1e48

# 資料清理規則
cleaning:
  remove_outliers: true
  outlier_threshold: 5.0  # 標準差倍數
  forward_fill_limit: 4   # 前向填充最大間隔
  backward_fill_limit: 4  # 後向填充最大間隔
  min_data_quality: 0.95  # 最小資料品質閾值

# 頻率對齊
frequency_alignment:
  default_frequency: "1h"
  supported_frequencies:
    - "1m"
    - "5m"
    - "15m"
    - "30m"
    - "1h"
    - "4h"
    - "1d"
  
  resample_methods:
    price: "ohlc"
    volume: "sum"
    pool_metrics: "last"
